### ISSUE TITLE
find() throws std::out_of_range: Index out of range in basic_string_view::substr thrown 

### ISSUE THREAD

**Issue by xgcssch** [bitwizeshift/string_view-standalone#6]
Hello!

Thanks for your library!
I am so happy to use it in a project on a z/OS (IBM Host) for efficient coding a DB2 Stored Procedure. 

During development i found the following problem:

```
bpstd::string_view s1 = "01234567890ABCDEFGHIJ";
bpstd::string_view s2 = "01";
BOOST_CHECK( s1.find( s2 ) != bpstd::string_view::npos );
BOOST_CHECK( s1.size() > 10 );
BOOST_CHECK( s1.find( s2, 10 ) == bpstd::string_view::npos ); // <- This line will throw std::out_of_range

```
In find() the code is
```
   ...
    const auto offset = pos;
    const auto increments = size() - v.size();

    for ( auto i = 0u; i <= increments; ++i )
    {
   ...

```
I fixed the problem by changing the second line to

```
    const auto increments = size() - v.size() - offset;
```
as increments should compensate for the given offset.

Best regards
Sönke

**Comment by bitwizeshift** [comment]
Hi @xgcssch, thank you for the bug report and the suggested fix! Since it sounds like you have the fix already prepared, you are more than welcome to open a pull request for this and I can merge it in 🙂 

If not, then I will make the change when I have a few extra cycles to focus on this repo.

----

Sorry for taking a week to respond to this; Github apparently didn't notify me that there were any open issues.

**Comment by xgcssch** [comment]
Threre it comes!
Best regards Sönke
